name: Build and deploy ASP.Net Core app to Azure Web App - lab5-backend-devin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./Backend/Backend.csproj

      - name: Build with dotnet
        run: dotnet build ./Backend/Backend.csproj --configuration Release --no-restore

      - name: Publish with dotnet
        run: dotnet publish ./Backend/Backend.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lab5-backend-devin'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_09649B91275D4A6AB0F057ADCB6557D3 }}
